spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 172.16.47.111
    port: 5672
    username: admin
    password: admin
  spring:
  sleuth:
    sampler:
      probability: 0.1
       
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    
zuul:
  routes:
    item-server: /item-server/**
    user-server: /user-server/**
    order-server: /order-server/**
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
